export const navLinks = [
  {
    id: 'home',
    title: 'Home',
  },
  {
    id: 'features',
    title: 'Features',
  },
  {
    id: 'product',
    title: 'Product',
  },
  {
    id: 'clients',
    title: 'Clients',
  },
];
export const events = [
  {
    id: 1,
    status: 'published',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2025-05-04 14:30:00',
  },
  {
    id: 2,
    status: 'assigned',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2025-05-04 14:30:00',
  },
  {
    id: 3,
    status: 'closed',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-08 14:30:00',
  },
  {
    id: 4,
    status: 'published',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2024-05-04 14:30:00',
  },
  {
    id: 5,
    status: 'assigned',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-04 14:30:00',
  },
  {
    id: 6,
    status: 'closed',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-08 14:30:00',
  },
  {
    id: 7,
    status: 'assigned',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-04 14:30:00',
  },
  {
    id: 8,
    status: 'closed',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-08 14:30:00',
  },
  {
    id: 9,
    status: 'assigned',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-04 14:30:00',
  },
  {
    id: 10,
    status: 'closed',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-08 14:30:00',
  },
];
