export const navLinks = [
  {
    id: 'home',
    title: 'Home',
  },
  {
    id: 'features',
    title: 'Features',
  },
  {
    id: 'product',
    title: 'Product',
  },
  {
    id: 'clients',
    title: 'Clients',
  },
];
export const events = [
  {
    id: 1,
    status: 'published',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2025-05-04 14:30:00',
  },
  {
    id: 2,
    status: 'assigned',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2025-05-04 14:30:00',
  },
  {
    id: 3,
    status: 'closed',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-08 14:30:00',
  },
  {
    id: 4,
    status: 'published',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2024-05-04 14:30:00',
  },
  {
    id: 5,
    status: 'assigned',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-04 14:30:00',
  },
  {
    id: 6,
    status: 'closed',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-08 14:30:00',
  },
  {
    id: 7,
    status: 'closed',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-08 14:30:00',
  },
  {
    id: 8,
    status: 'closed',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-08 14:30:00',
  },
  {
    id: 9,
    status: 'closed',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-08 14:30:00',
  },
  {
    id: 10,
    status: 'closed',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-08 14:30:00',
  },
  {
    id: 11,
    status: 'closed',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-08 14:30:00',
  },
  {
    id: 12,
    status: 'closed',
    bandName: 'The Beatles',
    MusicalType: 'jazz',
    registered: 'John Lennon',
    date: '2022-05-08 14:30:00',
  },
  {
    id: 13,
    status: 'assigned',
    bandName: 'Metallica',
    MusicalType: 'metal',
    registered: 'James Hetfield',
    date: '2023-06-03 21:30:00',
  },
  {
    id: 14,
    status: 'published',
    bandName: "Guns N' Roses",
    MusicalType: 'rock',
    registered: 'Axl Rose',
    date: '2023-06-07 19:00:00',
  },
  {
    id: 15,
    status: 'closed',
    bandName: 'Nirvana',
    MusicalType: 'grunge',
    registered: 'Kurt Cobain',
    date: '2023-06-10 20:00:00',
  },
  {
    id: 16,
    status: 'published',
    bandName: 'Red Hot Chili Peppers',
    MusicalType: 'rock',
    registered: 'Anthony Kiedis',
    date: '2023-06-15 21:00:00',
  },
  {
    id: 17,
    status: 'assigned',
    bandName: 'Green Day',
    MusicalType: 'punk',
    registered: 'Billie Joe Armstrong',
    date: '2023-06-20 19:30:00',
  },
  {
    id: 18,
    status: 'published',
    bandName: 'Foo Fighters',
    MusicalType: 'rock',
    registered: 'Dave Grohl',
    date: '2023-06-25 21:00:00',
  },
  {
    id: 19,
    status: 'closed',
    bandName: 'Pearl Jam',
    MusicalType: 'grunge',
    registered: 'Eddie Vedder',
    date: '2023-06-30 20:00:00',
  },
  {
    id: 20,
    status: 'published',
    bandName: 'System Of A Down',
    MusicalType: 'metal',
    registered: 'Serj Tankian',
    date: '2023-07-05 21:30:00',
  },
];
